### ISSUE TITLE
Errore con layer Raster

### ISSUE THREAD

**Issue by brunellop** [Korto19/TocTable#4]
Buongiorno Giulio,
In QGIS 3.34 ho utilizzato il suo ottimo plugin e ho riscontrato che funziona solo se sono presenti all'interno file vettoriali, se sono collegati file Raster o servizi WMS, il comando va in errore non producendo la tabella riassuntiva dei layer del progetto.

Buona giornata.

Paolo Brunello

**Comment by Korto19** [comment]
Buongiorno Brunello,
ho provveduto a modificare codice in merito.
Grazie della segnalazione e dell'apprezzamento.
Cordiali Saluti

**Comment by brunellop** [comment]
Buongiorno ,
Ho reinstallato il plugin, ottimo!
Grazie mille.
Saluti

**Comment by pigreco** [comment]
Grazie mille @Korto19
